import Link from "next/link";
import Navbar from "@/components/Navbar";
import { getCashfreeOrder } from "@/lib/cashfree";
import { db } from "@/db";
import { bookings } from "@/db/schema";
import { eq } from "drizzle-orm";
import { SITE, telLink, waLink } from "@/lib/site";
import { T } from "@/lib/lang";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import { getCashfreeOrder } from "@/lib/cashfree";
import { db } from "@/db";
import { bookings } from "@/db/schema";
import { eq } from "drizzle-orm";
import { SITE, telLink, waLink } from "@/lib/site";
import { T } from "@/lib/lang";
import { sendWhatsAppNotification, formatBookingNotification } from "@/lib/notify";
